# Generated by Django 5.0.4 on 2024-04-24 13:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_todo_addtime_todo_details_todo_finishtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='addtime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='todo',
            name='finishtime',
            field=models.DateField(default=None),
        ),
    ]
